#cloud-config
runcmd:
 - sysctl vm.swappiness=10
 - [ sh, -xc, "echo vm.swappiness=10 >> /etc/sysctl.conf" ]
 - git clone https://github.com/digitalbazaar/bedrock-ledger-test.git
 - cd bedrock-ledger-test
 - [ sh, -xc, "echo dashboard-hostname: _DASHBOARD_ >> ./instance-config.yml" ]
 - [ sh, -xc, "echo mongo-hostname: _MONGOSERVER_ >> ./instance-config.yml" ]
 - [ sh, -xc, "echo mongo-dbname: $(uuidgen) >> ./instance-config.yml" ]
 #- npm install --registry http://10.60.80.55:4873
 - npm install
 - node ./primary/index.js compile-less
 - npm run primary-aws >/dev/null 2>&1
