#cloud-config
runcmd:
 - echo 127.0.0.1 bedrock.local >> /etc/hosts
 - git clone https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity.git
 - cd /bedrock-ledger-consensus-continuity
 - git checkout xBranchTest
 - npm install
 - cd /bedrock-ledger-consensus-continuity/test
 - npm install
 - ./loop.sh
