#cloud-config
runcmd:
 - sysctl vm.swappiness=10
 - [ sh, -xc, "echo vm.swappiness=10 >> /etc/sysctl.conf" ]
 - umount /dev/vdb
 - mkfs.xfs -f /dev/vdb
 - sed -i '/^[/]dev[/]vdb/d' /etc/fstab
 - [ sh, -xc, "echo /dev/vdb /mnt/db xfs rw,nobarrier,auto 0 0 >> /etc/fstab" ]
 - mkdir /mnt/db
 - mount /dev/vdb /mnt/db
 - mkdir /mnt/db/mongodb
 - chown mongodb:mongodb /mnt/db/mongodb
 - curl -o /etc/mongod.conf https://gist.githubusercontent.com/mattcollier/f864a48b4044e00750c3f9afa481dbea/raw/mongod.conf
 - systemctl enable mongod
 - systemctl start mongod
