version: '3'

services:
  bedrock-ledger-test:
    # build:
      # context: .
      # dockerfile: Dockerfile
    image: digitalbazaar/bedrock-ledger-test:latest
    container_name: bedrock-ledger-test
    restart: unless-stopped
    depends_on:
      - mongo-docker
      - redis-docker
    env_file: docker-compose.env
    # environment:
    ports:
      - "18443:18443"
    # volumes:
    networks:
      - app-network
  mongo-docker:
    image: mongo:latest
    container_name: mongo-docker
    restart: unless-stopped
    # env_file: .env
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      # - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - /data/db:/data/db
    networks:
      - app-network
  redis-docker:
    image: redis:latest
    container_name: redis-docker
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    volumes:
      - /data/redis:/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
