version: '3'

services:
  bedrock-ledger-test:
    # build:
      # context: .
      # dockerfile: Dockerfile
    image: mattcollier/bedrock:bedrock-ledger-test
    container_name: bedrock-ledger-test
    restart: unless-stopped
    env_file: docker-compose.env
    # environment:
    ports:
      - "18443:18443"
    # volumes:
    networks:
      - app-network
  mongo-docker:
    image: mongo:latest
    container_name: mongo-docker
    restart: unless-stopped
    # env_file: .env
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      # - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    # volumes:
      # - dbdata:/data/db
    networks:
      - app-network
  redis-docker:
    image: redis:latest
    container_name: redis-docker
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
